# Generated by Django 2.1.1 on 2019-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crawl_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
